version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: pizzeriadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pizzeriadb
    ports:
      - "3308:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d